-- =====================================================================
-- E-Menu Platform: Generate Roles for ALL Existing Businesses
-- Run this in pgAdmin - it dynamically finds all businesses and
-- creates the full set of roles for each one.
-- Safe to run multiple times (skips duplicates).
-- =====================================================================

-- =====================================================================
-- 0. DROP OLD CHECK CONSTRAINT ON ROLE NAME
--    This was auto-generated by Hibernate when 'name' was an enum.
--    Now that roles are dynamic (String), this constraint must be removed.
--    Safe to run if constraint doesn't exist (will just show a notice).
-- =====================================================================
ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_name_check;

-- =====================================================================
-- 1. INSERT BUSINESS ROLES FOR EVERY EXISTING BUSINESS
--    Each business gets: MANAGER, CASHIER, WAITER, CHEF, DELIVERY
--    These are BUSINESS_USER type roles scoped to each business.
-- =====================================================================
INSERT INTO roles (id, name, display_name, description, business_id, user_type, version, is_deleted, created_at, updated_at, created_by, updated_by)
SELECT
    gen_random_uuid(),
    role_def.name,
    role_def.display_name,
    role_def.description,
    b.id,
    'BUSINESS_USER',
    0,
    false,
    NOW(),
    NOW(),
    'system',
    'system'
FROM businesses b
CROSS JOIN (
    VALUES
        ('MANAGER',    'Manager',    'Full operational access to manage the business'),
        ('CASHIER',    'Cashier',    'Handles payments, billing, and transactions'),
        ('WAITER',     'Waiter',     'Takes orders and serves customers'),
        ('CHEF',       'Chef',       'Kitchen staff managing food preparation'),
        ('DELIVERY',   'Delivery',   'Handles food delivery to customers'),
        ('INVENTORY',  'Inventory',  'Manages stock and inventory tracking'),
        ('RECEPTIONIST', 'Receptionist', 'Handles reservations and front desk')
) AS role_def(name, display_name, description)
WHERE b.is_deleted = false
AND NOT EXISTS (
    SELECT 1 FROM roles r
    WHERE r.name = role_def.name
    AND r.business_id = b.id
);

-- =====================================================================
-- 2. INSERT PLATFORM-LEVEL CUSTOMER ROLES
--    These are global roles (business_id = NULL) for the CUSTOMER platform.
-- =====================================================================
INSERT INTO roles (id, name, display_name, description, business_id, user_type, version, is_deleted, created_at, updated_at, created_by, updated_by)
SELECT
    gen_random_uuid(),
    role_def.name,
    role_def.display_name,
    role_def.description,
    NULL,
    'CUSTOMER',
    0,
    false,
    NOW(),
    NOW(),
    'system',
    'system'
FROM (
    VALUES
        ('CUSTOMER_VIP',      'Customer VIP',      'VIP customer with premium benefits and priority service'),
        ('CUSTOMER_REGULAR',  'Customer Regular',   'Standard registered customer'),
        ('CUSTOMER_GUEST',    'Customer Guest',     'Guest customer with limited access')
) AS role_def(name, display_name, description)
WHERE NOT EXISTS (
    SELECT 1 FROM roles r
    WHERE r.name = role_def.name
    AND r.business_id IS NULL
    AND r.is_deleted = false
);

-- =====================================================================
-- 3. INSERT PLATFORM-LEVEL ADMIN ROLES
--    Global roles (business_id = NULL) for PLATFORM_USER type.
-- =====================================================================
INSERT INTO roles (id, name, display_name, description, business_id, user_type, version, is_deleted, created_at, updated_at, created_by, updated_by)
SELECT
    gen_random_uuid(),
    role_def.name,
    role_def.display_name,
    role_def.description,
    NULL,
    'PLATFORM_USER',
    0,
    false,
    NOW(),
    NOW(),
    'system',
    'system'
FROM (
    VALUES
        ('PLATFORM_ADMIN',    'Platform Admin',     'Administrative access to manage the entire platform'),
        ('PLATFORM_SUPPORT',  'Platform Support',   'Customer support and issue resolution'),
        ('PLATFORM_ANALYST',  'Platform Analyst',   'Analytics and reporting access across the platform')
) AS role_def(name, display_name, description)
WHERE NOT EXISTS (
    SELECT 1 FROM roles r
    WHERE r.name = role_def.name
    AND r.business_id IS NULL
    AND r.is_deleted = false
);

-- =====================================================================
-- 4. VERIFICATION: Check what was generated
-- =====================================================================

-- Show all roles grouped by business
SELECT
    COALESCE(b.name, '-- PLATFORM (global) --') AS business_name,
    r.name AS role_name,
    r.display_name,
    r.user_type,
    r.created_at
FROM roles r
LEFT JOIN businesses b ON r.business_id = b.id
WHERE r.is_deleted = false
ORDER BY b.name NULLS FIRST, r.user_type, r.name;

-- Count summary
SELECT
    (SELECT COUNT(*) FROM roles WHERE is_deleted = false AND business_id IS NOT NULL) AS business_roles,
    (SELECT COUNT(*) FROM roles WHERE is_deleted = false AND user_type = 'CUSTOMER') AS customer_roles,
    (SELECT COUNT(*) FROM roles WHERE is_deleted = false AND user_type = 'PLATFORM_USER') AS platform_roles,
    (SELECT COUNT(*) FROM roles WHERE is_deleted = false) AS total_roles,
    (SELECT COUNT(*) FROM businesses WHERE is_deleted = false) AS total_businesses;
